name: Run get_site_content.py
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium pystache

      - name: Run script
        run: python get_site_content.py

      - name: Commit and push if it changed
        run: |
          git diff
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Action"
          git pull origin gh_pages || exit 0
          git add rss_test.xml || exit 0
          git commit -m "Update rss_test.xml" || exit 0
          git push origin gh_pages
